// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globals

type Globals struct {
	// A long winded, multi-line description
	// for the query parameter number one.
	//
	QueryParam1 *string `queryParam:"style=form,explode=true,name=queryParam1"`
	// A deprecated description
	//
	// Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
	DeprecatedQueryParam1 *string `queryParam:"style=form,explode=true,name=deprecatedQueryParam1"`
	// Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
	DeprecatedQueryParam2 *string `queryParam:"style=form,explode=true,name=deprecatedQueryParam2"`
	LoneQueryParam        *string `queryParam:"style=form,explode=true,name=loneQueryParam"`
}

func (o *Globals) GetQueryParam1() *string {
	if o == nil {
		return nil
	}
	return o.QueryParam1
}

func (o *Globals) GetDeprecatedQueryParam1() *string {
	if o == nil {
		return nil
	}
	return o.DeprecatedQueryParam1
}

func (o *Globals) GetDeprecatedQueryParam2() *string {
	if o == nil {
		return nil
	}
	return o.DeprecatedQueryParam2
}

func (o *Globals) GetLoneQueryParam() *string {
	if o == nil {
		return nil
	}
	return o.LoneQueryParam
}
