// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
	"github.com/tristanspeakeasy/sdk-platform-test/types/stream"
)

type ChatRequestBody struct {
	Prompt *string `json:"prompt,omitempty"`
}

func (c *ChatRequestBody) GetPrompt() *string {
	if c == nil {
		return nil
	}
	return c.Prompt
}

type Data struct {
	Content *string `json:"content,omitempty"`
}

func (d *Data) GetContent() *string {
	if d == nil {
		return nil
	}
	return d.Content
}

// ChatChatStream - A stream containing chat completion tokens
type ChatChatStream struct {
	Data Data `json:"data"`
}

func (c *ChatChatStream) GetData() Data {
	if c == nil {
		return Data{}
	}
	return c.Data
}

func (c ChatChatStream) GetEventEncoding(event string) (string, error) {
	return "application/json", nil
}

type ChatResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A stream containing chat completion tokens
	ChatStream *stream.EventStream[ChatChatStream]
}

func (c *ChatResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ChatResponse) GetChatStream() *stream.EventStream[ChatChatStream] {
	if c == nil {
		return nil
	}
	return c.ChatStream
}
