// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

var Deprecated1ServerList = []string{
	"http://localhost:12345",
}

type Deprecated1Response struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *Deprecated1Response) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
