// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

type GetFullyFlattenedRequestSecurity struct {
	APIKey *string `security:"scheme,type=apiKey,subtype=header,name=api_key,env=sdk_api_key"`
}

func (g *GetFullyFlattenedRequestSecurity) GetAPIKey() *string {
	if g == nil {
		return nil
	}
	return g.APIKey
}

type Emoji string

const (
	EmojiWave     Emoji = "wave"
	EmojiSmiley   Emoji = "smiley"
	EmojiThumbsup Emoji = "thumbsup"
	EmojiTada     Emoji = "tada"
)

func (e Emoji) ToPointer() *Emoji {
	return &e
}
func (e *Emoji) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "wave":
		fallthrough
	case "smiley":
		fallthrough
	case "thumbsup":
		fallthrough
	case "tada":
		*e = Emoji(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Emoji: %v", v)
	}
}

type GetFullyFlattenedRequestRequestBody struct {
	Name    string  `json:"name"`
	Emoji   *Emoji  `json:"emoji,omitempty"`
	Gif     *string `json:"gif,omitempty"`
	Reply   *bool   `json:"reply,omitempty"`
	Private *bool   `json:"private,omitempty"`
}

func (g *GetFullyFlattenedRequestRequestBody) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetFullyFlattenedRequestRequestBody) GetEmoji() *Emoji {
	if g == nil {
		return nil
	}
	return g.Emoji
}

func (g *GetFullyFlattenedRequestRequestBody) GetGif() *string {
	if g == nil {
		return nil
	}
	return g.Gif
}

func (g *GetFullyFlattenedRequestRequestBody) GetReply() *bool {
	if g == nil {
		return nil
	}
	return g.Reply
}

func (g *GetFullyFlattenedRequestRequestBody) GetPrivate() *bool {
	if g == nil {
		return nil
	}
	return g.Private
}

type GetFullyFlattenedRequestRequest struct {
	Lang        string                              `queryParam:"style=form,explode=true,name=lang"`
	MaxLength   *int64                              `queryParam:"style=form,explode=true,name=max_length"`
	RequestBody GetFullyFlattenedRequestRequestBody `request:"mediaType=application/json"`
}

func (g *GetFullyFlattenedRequestRequest) GetLang() string {
	if g == nil {
		return ""
	}
	return g.Lang
}

func (g *GetFullyFlattenedRequestRequest) GetMaxLength() *int64 {
	if g == nil {
		return nil
	}
	return g.MaxLength
}

func (g *GetFullyFlattenedRequestRequest) GetRequestBody() GetFullyFlattenedRequestRequestBody {
	if g == nil {
		return GetFullyFlattenedRequestRequestBody{}
	}
	return g.RequestBody
}

type GetFullyFlattenedRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (g *GetFullyFlattenedRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}
