// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/tristanspeakeasy/sdk-platform-test/internal/utils"
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

type OneOfWithUnionDescriptionType string

const (
	OneOfWithUnionDescriptionTypeExhaustiveObject OneOfWithUnionDescriptionType = "ExhaustiveObject"
	OneOfWithUnionDescriptionTypeSimpleObject     OneOfWithUnionDescriptionType = "SimpleObject"
)

// OneOfWithUnionDescription - A union of two types.
type OneOfWithUnionDescription struct {
	ExhaustiveObject *components.ExhaustiveObject `queryParam:"inline" name:"oneOfWithUnionDescription"`
	SimpleObject     *components.SimpleObject     `queryParam:"inline" name:"oneOfWithUnionDescription"`

	Type OneOfWithUnionDescriptionType
}

func CreateOneOfWithUnionDescriptionExhaustiveObject(exhaustiveObject components.ExhaustiveObject) OneOfWithUnionDescription {
	typ := OneOfWithUnionDescriptionTypeExhaustiveObject

	return OneOfWithUnionDescription{
		ExhaustiveObject: &exhaustiveObject,
		Type:             typ,
	}
}

func CreateOneOfWithUnionDescriptionSimpleObject(simpleObject components.SimpleObject) OneOfWithUnionDescription {
	typ := OneOfWithUnionDescriptionTypeSimpleObject

	return OneOfWithUnionDescription{
		SimpleObject: &simpleObject,
		Type:         typ,
	}
}

func (u *OneOfWithUnionDescription) UnmarshalJSON(data []byte) error {

	var exhaustiveObject components.ExhaustiveObject = components.ExhaustiveObject{}
	if err := utils.UnmarshalJSON(data, &exhaustiveObject, "", true, nil); err == nil {
		u.ExhaustiveObject = &exhaustiveObject
		u.Type = OneOfWithUnionDescriptionTypeExhaustiveObject
		return nil
	}

	var simpleObject components.SimpleObject = components.SimpleObject{}
	if err := utils.UnmarshalJSON(data, &simpleObject, "", true, nil); err == nil {
		u.SimpleObject = &simpleObject
		u.Type = OneOfWithUnionDescriptionTypeSimpleObject
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for OneOfWithUnionDescription", string(data))
}

func (u OneOfWithUnionDescription) MarshalJSON() ([]byte, error) {
	if u.ExhaustiveObject != nil {
		return utils.MarshalJSON(u.ExhaustiveObject, "", true)
	}

	if u.SimpleObject != nil {
		return utils.MarshalJSON(u.SimpleObject, "", true)
	}

	return nil, errors.New("could not marshal union type OneOfWithUnionDescription: all fields are null")
}

type SimpleAllOf struct {
	// A string property.
	Str *string `json:"str,omitempty"`
	// A boolean property.
	Bool *bool `json:"bool,omitempty"`
}

func (s *SimpleAllOf) GetStr() *string {
	if s == nil {
		return nil
	}
	return s.Str
}

func (s *SimpleAllOf) GetBool() *bool {
	if s == nil {
		return nil
	}
	return s.Bool
}

// AllOfWithFactoredOutProperties - An object with allOf and factored out properties.
type AllOfWithFactoredOutProperties struct {
	// An overriding property.
	AnOverridingProperty *string `json:"anOverridingProperty,omitempty"`
	// Another property.
	AnotherProperty *string `json:"anotherProperty,omitempty"`
	// An extra property.
	AnExtraProperty *string `json:"anExtraProperty,omitempty"`
}

func (a *AllOfWithFactoredOutProperties) GetAnOverridingProperty() *string {
	if a == nil {
		return nil
	}
	return a.AnOverridingProperty
}

func (a *AllOfWithFactoredOutProperties) GetAnotherProperty() *string {
	if a == nil {
		return nil
	}
	return a.AnotherProperty
}

func (a *AllOfWithFactoredOutProperties) GetAnExtraProperty() *string {
	if a == nil {
		return nil
	}
	return a.AnExtraProperty
}

type GetPolymorphismResponseBody struct {
	// A union of two types.
	OneOfWithUnionDescription *OneOfWithUnionDescription `json:"oneOfWithUnionDescription,omitempty"`
	// A union of two types with factored out properties.
	OneOfWithFactoredOutProperties *components.OneOfWithFactoredOutProperties `json:"oneOfWithFactoredOutProperties,omitempty"`
	SimpleAllOf                    *SimpleAllOf                               `json:"simpleAllOf,omitempty"`
	// An object with allOf and factored out properties.
	AllOfWithFactoredOutProperties *AllOfWithFactoredOutProperties `json:"allOfWithFactoredOutProperties,omitempty"`
	CircularUnion                  *components.CircularUnion       `json:"circularUnion,omitempty"`
}

func (g *GetPolymorphismResponseBody) GetOneOfWithUnionDescription() *OneOfWithUnionDescription {
	if g == nil {
		return nil
	}
	return g.OneOfWithUnionDescription
}

func (g *GetPolymorphismResponseBody) GetOneOfWithFactoredOutProperties() *components.OneOfWithFactoredOutProperties {
	if g == nil {
		return nil
	}
	return g.OneOfWithFactoredOutProperties
}

func (g *GetPolymorphismResponseBody) GetSimpleAllOf() *SimpleAllOf {
	if g == nil {
		return nil
	}
	return g.SimpleAllOf
}

func (g *GetPolymorphismResponseBody) GetAllOfWithFactoredOutProperties() *AllOfWithFactoredOutProperties {
	if g == nil {
		return nil
	}
	return g.AllOfWithFactoredOutProperties
}

func (g *GetPolymorphismResponseBody) GetCircularUnion() *components.CircularUnion {
	if g == nil {
		return nil
	}
	return g.CircularUnion
}

type GetPolymorphismResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *GetPolymorphismResponseBody
}

func (g *GetPolymorphismResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPolymorphismResponse) GetObject() *GetPolymorphismResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
