// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

type GetRequestBodyFlattenedAwayGlobals struct {
	LoneQueryParam *string `queryParam:"style=form,explode=true,name=loneQueryParam"`
}

func (o *GetRequestBodyFlattenedAwayGlobals) GetLoneQueryParam() *string {
	if o == nil {
		return nil
	}
	return o.LoneQueryParam
}

type GetRequestBodyFlattenedAwayRequest struct {
}

type GetRequestBodyFlattenedAwayResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *GetRequestBodyFlattenedAwayResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
