// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

type GetRequestBodyFlattenedAwayGlobals struct {
	LoneQueryParam *string `queryParam:"style=form,explode=true,name=loneQueryParam"`
}

func (g *GetRequestBodyFlattenedAwayGlobals) GetLoneQueryParam() *string {
	if g == nil {
		return nil
	}
	return g.LoneQueryParam
}

type GetRequestBodyFlattenedAwayRequest struct {
}

type GetRequestBodyFlattenedAwayResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (g *GetRequestBodyFlattenedAwayResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}
