// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

type GetUnionErrorsRequest struct {
	Page int64 `queryParam:"style=form,explode=true,name=page"`
}

func (g *GetUnionErrorsRequest) GetPage() int64 {
	if g == nil {
		return 0
	}
	return g.Page
}

// GetUnionErrorsResponseBody - OK
type GetUnionErrorsResponseBody struct {
	Pages []string `json:"pages"`
}

func (g *GetUnionErrorsResponseBody) GetPages() []string {
	if g == nil {
		return []string{}
	}
	return g.Pages
}

type GetUnionErrorsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *GetUnionErrorsResponseBody

	Next func() (*GetUnionErrorsResponse, error)
}

func (g *GetUnionErrorsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUnionErrorsResponse) GetObject() *GetUnionErrorsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
