// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

type GetUserRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetUserRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	User *components.User
}

func (g *GetUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUserResponse) GetUser() *components.User {
	if g == nil {
		return nil
	}
	return g.User
}
