// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/tristanspeakeasy/sdk-platform-test/internal/utils"
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

const (
	// The only server.
	ListTest1ServerMain string = "Main"
)

var ListTest1ServerList = map[string]string{
	// The only server.
	ListTest1ServerMain: "http://localhost:35123",
}

type ListTest1Globals struct {
	// A long winded, multi-line description
	// for the query parameter number one.
	//
	QueryParam1 *string `queryParam:"style=form,explode=true,name=queryParam1"`
}

func (l *ListTest1Globals) GetQueryParam1() *string {
	if l == nil {
		return nil
	}
	return l.QueryParam1
}

type ListTest1Security struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=api_key,env=sdk_api_key"`
}

func (l *ListTest1Security) GetAPIKey() string {
	if l == nil {
		return ""
	}
	return l.APIKey
}

// QueryParam2 - A enum query parameter.
type QueryParam2 int64

const (
	QueryParam2Zero QueryParam2 = 0
	QueryParam2One  QueryParam2 = 1
	QueryParam2Two  QueryParam2 = 2
)

func (e QueryParam2) ToPointer() *QueryParam2 {
	return &e
}
func (e *QueryParam2) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		fallthrough
	case 2:
		*e = QueryParam2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParam2: %v", v)
	}
}

type ListTest1Request struct {
	QueryParam1 *string `queryParam:"style=form,explode=true,name=queryParam1"`
	// A enum query parameter.
	QueryParam2  QueryParam2 `queryParam:"style=form,explode=true,name=queryParam2"`
	Page         int64       `pathParam:"style=simple,explode=false,name=page"`
	HeaderParam1 string      `header:"style=simple,explode=false,name=headerParam1"`
}

func (l *ListTest1Request) GetQueryParam1() *string {
	if l == nil {
		return nil
	}
	return l.QueryParam1
}

func (l *ListTest1Request) GetQueryParam2() QueryParam2 {
	if l == nil {
		return QueryParam2(0)
	}
	return l.QueryParam2
}

func (l *ListTest1Request) GetPage() int64 {
	if l == nil {
		return 0
	}
	return l.Page
}

func (l *ListTest1Request) GetHeaderParam1() string {
	if l == nil {
		return ""
	}
	return l.HeaderParam1
}

type ResultArray struct {
	Test1 string `json:"test1"`
}

func (r *ResultArray) GetTest1() string {
	if r == nil {
		return ""
	}
	return r.Test1
}

// ListTest1ResponseBody - OK
type ListTest1ResponseBody struct {
	ResultArray []ResultArray    `json:"resultArray"`
	TotalCount  int64            `json:"totalCount"`
	Type        *components.Enum `default:"First" json:"type"`
}

func (l ListTest1ResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTest1ResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"resultArray", "totalCount"}); err != nil {
		return err
	}
	return nil
}

func (l *ListTest1ResponseBody) GetResultArray() []ResultArray {
	if l == nil {
		return []ResultArray{}
	}
	return l.ResultArray
}

func (l *ListTest1ResponseBody) GetTotalCount() int64 {
	if l == nil {
		return 0
	}
	return l.TotalCount
}

func (l *ListTest1ResponseBody) GetType() *components.Enum {
	if l == nil {
		return nil
	}
	return l.Type
}

type ListTest1Response struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *ListTest1ResponseBody

	Next func() (*ListTest1Response, error)
}

func (l *ListTest1Response) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTest1Response) GetObject() *ListTest1ResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
