// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

type OperationWithLeadingAndTrailingUnderscoresResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OperationWithLeadingAndTrailingUnderscoresResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
