// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
	"io"
)

type PostFileRequestBody struct {
	// A file
	File components.File `multipartForm:"file,name=file"`
}

func (p *PostFileRequestBody) GetFile() components.File {
	if p == nil {
		return components.File{}
	}
	return p.File
}

type PostFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	File io.ReadCloser
}

func (p *PostFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostFileResponse) GetFile() io.ReadCloser {
	if p == nil {
		return nil
	}
	return p.File
}
