// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

type TestEndpointRequestBody struct {
	Test string `json:"test"`
}

func (o *TestEndpointRequestBody) GetTest() string {
	if o == nil {
		return ""
	}
	return o.Test
}

type TestEndpointRequest struct {
	TestName    string                  `pathParam:"style=simple,explode=false,name=testName"`
	RequestBody TestEndpointRequestBody `request:"mediaType=application/json"`
}

func (o *TestEndpointRequest) GetTestName() string {
	if o == nil {
		return ""
	}
	return o.TestName
}

func (o *TestEndpointRequest) GetRequestBody() TestEndpointRequestBody {
	if o == nil {
		return TestEndpointRequestBody{}
	}
	return o.RequestBody
}

type TestEndpointResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *TestEndpointResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
