// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

type UpdateUserRequest struct {
	ID   string          `pathParam:"style=simple,explode=false,name=id"`
	User components.User `request:"mediaType=application/json"`
}

func (u *UpdateUserRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateUserRequest) GetUser() components.User {
	if u == nil {
		return components.User{}
	}
	return u.User
}

type UpdateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	User *components.User
}

func (u *UpdateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateUserResponse) GetUser() *components.User {
	if u == nil {
		return nil
	}
	return u.User
}
