// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetPolymorphism(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "getPolymorphism[0]":
			dir.HandlerFunc("getPolymorphism", testGetPolymorphismGetPolymorphism0)(w, req)
		default:
			http.Error(w, "Unknown test: "+test, http.StatusBadRequest)
		}
	}
}

func testGetPolymorphismGetPolymorphism0(w http.ResponseWriter, req *http.Request) {
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	respBody := &operations.GetPolymorphismResponseBody{
		OneOfWithUnionDescription: types.Pointer(operations.CreateOneOfWithUnionDescriptionSimpleObject(
			components.SimpleObject{
				Str: "example",
			},
		)),
		OneOfWithFactoredOutProperties: types.Pointer(components.CreateOneOfWithFactoredOutPropertiesOneOfWithFactoredOutPropertiesSimpleObject(
			components.OneOfWithFactoredOutPropertiesSimpleObject{
				Str:             "example",
				AnExtraProperty: types.String("example"),
			},
		)),
		SimpleAllOf: &operations.SimpleAllOf{
			Str:  types.String("example"),
			Bool: types.Bool(true),
		},
		AllOfWithFactoredOutProperties: &operations.AllOfWithFactoredOutProperties{
			AnOverridingProperty: types.String("example"),
			AnotherProperty:      types.String("example"),
			AnExtraProperty:      types.String("example"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
