// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	sdkplatformtest "github.com/tristanspeakeasy/sdk-platform-test"
	"github.com/tristanspeakeasy/sdk-platform-test/internal/utils"
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
	"github.com/tristanspeakeasy/sdk-platform-test/models/operations"
	"testing"
)

func TestTag1_Deprecated1(t *testing.T) {
	ctx := context.Background()

	s := sdkplatformtest.New(
		sdkplatformtest.WithClient(createTestHTTPClient("deprecated1")),
	)

	res, err := s.Tag1.Deprecated1(ctx, operations.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")))
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestTag1_ListTest1(t *testing.T) {
	ctx := context.Background()

	s := sdkplatformtest.New(
		sdkplatformtest.WithClient(createTestHTTPClient("listTest1")),
	)

	res, err := s.Tag1.ListTest1(ctx, operations.ListTest1Security{
		APIKey: "some-api-key",
	}, operations.QueryParam2One, 100, "some example header param", sdkplatformtest.String("some example query param"), operations.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")))
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Object)
	assert.Equal(t, &operations.ListTest1ResponseBody{
		ResultArray: []operations.ResultArray{
			operations.ResultArray{
				Test1: "some example response",
			},
		},
		TotalCount: 100,
		Type:       components.EnumFirst.ToPointer(),
	}, res.Object)

}
