// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BaseUser struct {
	ID            *string   `json:"id,omitempty"`
	Email         string    `json:"email"`
	FirstName     *string   `json:"first_name,omitempty"`
	LastName      *string   `json:"last_name,omitempty"`
	Age           *float64  `json:"age,omitempty"`
	PostalCode    *string   `json:"postal_code,omitempty"`
	AssociatedIds []string  `json:"associatedIds,omitempty"`
	Metadata      *Metadata `json:"metadata,omitempty"`
}

func (b *BaseUser) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *BaseUser) GetEmail() string {
	if b == nil {
		return ""
	}
	return b.Email
}

func (b *BaseUser) GetFirstName() *string {
	if b == nil {
		return nil
	}
	return b.FirstName
}

func (b *BaseUser) GetLastName() *string {
	if b == nil {
		return nil
	}
	return b.LastName
}

func (b *BaseUser) GetAge() *float64 {
	if b == nil {
		return nil
	}
	return b.Age
}

func (b *BaseUser) GetPostalCode() *string {
	if b == nil {
		return nil
	}
	return b.PostalCode
}

func (b *BaseUser) GetAssociatedIds() []string {
	if b == nil {
		return nil
	}
	return b.AssociatedIds
}

func (b *BaseUser) GetMetadata() *Metadata {
	if b == nil {
		return nil
	}
	return b.Metadata
}
