// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ErrorType2Error struct {
	Message string `json:"message"`
}

func (o *ErrorType2Error) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

type ErrorType2 struct {
	Error ErrorType2Error `json:"error"`
}

func (o *ErrorType2) GetError() ErrorType2Error {
	if o == nil {
		return ErrorType2Error{}
	}
	return o.Error
}
