// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/tristanspeakeasy/sdk-platform-test/internal/utils"
	"github.com/tristanspeakeasy/sdk-platform-test/types"
)

type ErrorType1 struct {
	code  *string `const:"rate_limit_exceeded" json:"code"`
	Error string  `json:"error"`
}

func (e ErrorType1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ErrorType1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"error"}); err != nil {
		return err
	}
	return nil
}

func (e *ErrorType1) GetCode() *string {
	return types.Pointer("rate_limit_exceeded")
}

func (e *ErrorType1) GetError() string {
	if e == nil {
		return ""
	}
	return e.Error
}
