// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type File struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (f *File) GetFileName() string {
	if f == nil {
		return ""
	}
	return f.FileName
}

func (f *File) GetContent() any {
	if f == nil {
		return nil
	}
	return f.Content
}
