// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SecurityOption1 struct {
	Username string `security:"scheme,type=http,subtype=basic,name=username,env=sdk_username"`
	Password string `security:"scheme,type=http,subtype=basic,name=password,env=sdk_password"`
}

func (s *SecurityOption1) GetUsername() string {
	if s == nil {
		return ""
	}
	return s.Username
}

func (s *SecurityOption1) GetPassword() string {
	if s == nil {
		return ""
	}
	return s.Password
}

type SecurityOption2 struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization,env=sdk_bearer_auth"`
	APIKey     string `security:"scheme,type=apiKey,subtype=header,name=api_key,env=sdk_api_key"`
}

func (s *SecurityOption2) GetBearerAuth() string {
	if s == nil {
		return ""
	}
	return s.BearerAuth
}

func (s *SecurityOption2) GetAPIKey() string {
	if s == nil {
		return ""
	}
	return s.APIKey
}

type SecurityOption3 struct {
	Oauth2 string `security:"scheme,type=oauth2,name=Authorization,env=sdk_oauth2"`
}

func (s *SecurityOption3) GetOauth2() string {
	if s == nil {
		return ""
	}
	return s.Oauth2
}

type SecurityOption4 struct {
	AppID  string `json:"appId" security:"scheme,type=http,subtype=custom,name=appId,env=sdk_app_id"`
	Secret string `json:"secret" security:"scheme,type=http,subtype=custom,name=secret,env=sdk_secret"`
}

func (s *SecurityOption4) GetAppID() string {
	if s == nil {
		return ""
	}
	return s.AppID
}

func (s *SecurityOption4) GetSecret() string {
	if s == nil {
		return ""
	}
	return s.Secret
}

type SecurityOption5 struct {
	MobileAuth string `security:"scheme,type=oauth2,name=Authorization,env=sdk_mobile_auth"`
}

func (s *SecurityOption5) GetMobileAuth() string {
	if s == nil {
		return ""
	}
	return s.MobileAuth
}

type Security struct {
	Option1 *SecurityOption1 `security:"option"`
	Option2 *SecurityOption2 `security:"option"`
	Option3 *SecurityOption3 `security:"option"`
	Option4 *SecurityOption4 `security:"option"`
	Option5 *SecurityOption5 `security:"option"`
}

func (s *Security) GetOption1() *SecurityOption1 {
	if s == nil {
		return nil
	}
	return s.Option1
}

func (s *Security) GetOption2() *SecurityOption2 {
	if s == nil {
		return nil
	}
	return s.Option2
}

func (s *Security) GetOption3() *SecurityOption3 {
	if s == nil {
		return nil
	}
	return s.Option3
}

func (s *Security) GetOption4() *SecurityOption4 {
	if s == nil {
		return nil
	}
	return s.Option4
}

func (s *Security) GetOption5() *SecurityOption5 {
	if s == nil {
		return nil
	}
	return s.Option5
}
