// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/tristanspeakeasy/sdk-platform-test/internal/utils"
)

type Error struct {
	Message string `json:"message"`
}

func (o *Error) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

type TaggedError2 struct {
	tag   string `const:"tag2" json:"tag"`
	Error Error  `json:"error"`
}

func (t TaggedError2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaggedError2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TaggedError2) GetTag() string {
	return "tag2"
}

func (o *TaggedError2) GetError() Error {
	if o == nil {
		return Error{}
	}
	return o.Error
}
