// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/tristanspeakeasy/sdk-platform-test/internal/utils"
)

type Error struct {
	Message string `json:"message"`
}

func (e Error) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Error) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"message"}); err != nil {
		return err
	}
	return nil
}

func (e *Error) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

type TaggedError2 struct {
	tag   string `const:"tag2" json:"tag"`
	Error Error  `json:"error"`
}

func (t TaggedError2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaggedError2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"tag", "error"}); err != nil {
		return err
	}
	return nil
}

func (t *TaggedError2) GetTag() string {
	return "tag2"
}

func (t *TaggedError2) GetError() Error {
	if t == nil {
		return Error{}
	}
	return t.Error
}
