// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/tristanspeakeasy/sdk-platform-test/internal/utils"
)

type Tag string

const (
	TagTag1 Tag = "tag1"
)

func (e Tag) ToPointer() *Tag {
	return &e
}
func (e *Tag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tag1":
		*e = Tag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Tag: %v", v)
	}
}

type TaggedError1 struct {
	Tag   Tag    `json:"tag"`
	Error string `json:"error"`
}

func (t TaggedError1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaggedError1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"tag", "error"}); err != nil {
		return err
	}
	return nil
}

func (t *TaggedError1) GetTag() Tag {
	if t == nil {
		return Tag("")
	}
	return t.Tag
}

func (t *TaggedError1) GetError() string {
	if t == nil {
		return ""
	}
	return t.Error
}
