// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/tristanspeakeasy/sdk-platform-test/internal/utils"
	"github.com/tristanspeakeasy/sdk-platform-test/types"
)

type Test2Response struct {
	Test2     *string `json:"test2,omitempty"`
	someConst *string `const:"someConstValue" json:"someConst,omitempty"`
}

func (t Test2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Test2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Test2Response) GetTest2() *string {
	if t == nil {
		return nil
	}
	return t.Test2
}

func (t *Test2Response) GetSomeConst() *string {
	return types.Pointer("someConstValue")
}
