// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type User struct {
	ID            string    `json:"id"`
	Email         string    `json:"email"`
	FirstName     *string   `json:"first_name,omitempty"`
	LastName      *string   `json:"last_name,omitempty"`
	Age           *float64  `json:"age,omitempty"`
	PostalCode    *string   `json:"postal_code,omitempty"`
	AssociatedIds []string  `json:"associatedIds,omitempty"`
	Metadata      *Metadata `json:"metadata,omitempty"`
}

func (u *User) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *User) GetEmail() string {
	if u == nil {
		return ""
	}
	return u.Email
}

func (u *User) GetFirstName() *string {
	if u == nil {
		return nil
	}
	return u.FirstName
}

func (u *User) GetLastName() *string {
	if u == nil {
		return nil
	}
	return u.LastName
}

func (u *User) GetAge() *float64 {
	if u == nil {
		return nil
	}
	return u.Age
}

func (u *User) GetPostalCode() *string {
	if u == nil {
		return nil
	}
	return u.PostalCode
}

func (u *User) GetAssociatedIds() []string {
	if u == nil {
		return nil
	}
	return u.AssociatedIds
}

func (u *User) GetMetadata() *Metadata {
	if u == nil {
		return nil
	}
	return u.Metadata
}
