// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SimpleObject struct {
	// A string property.
	Str string `json:"str"`
}

func (o *SimpleObject) GetStr() string {
	if o == nil {
		return ""
	}
	return o.Str
}
