// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
)

type Test2Response struct {
	Test2     *string `json:"test2,omitempty"`
	someConst *string `const:"someConstValue" json:"someConst,omitempty"`
}

func (t Test2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Test2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Test2Response) GetTest2() *string {
	if o == nil {
		return nil
	}
	return o.Test2
}

func (o *Test2Response) GetSomeConst() *string {
	return types.String("someConstValue")
}
