workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    SDK Review:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/tristan-test/sdk-platform-test/sdk-review
targets:
    sdk-platform-test:
        target: go
        source: SDK Review
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/tristan-test/sdk-platform-test/sdk-review-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
        testing:
            enabled: true
