// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"encoding/json"
	"fmt"
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

type Type string

const (
	TypePaymentCreated Type = "payment.created"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "payment.created":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type PaymentCreatedRequestBody struct {
	// Payment amount
	Amount string `json:"amount"`
	Type   Type   `json:"type"`
}

func (p *PaymentCreatedRequestBody) GetAmount() string {
	if p == nil {
		return ""
	}
	return p.Amount
}

func (p *PaymentCreatedRequestBody) GetType() Type {
	if p == nil {
		return Type("")
	}
	return p.Type
}

type PaymentCreatedResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (p *PaymentCreatedResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}
