// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"encoding/json"
	"fmt"
	"github.com/tristanspeakeasy/sdk-platform-test/models/components"
)

type PaymentUpdatedType string

const (
	PaymentUpdatedTypePaymentUpdated PaymentUpdatedType = "payment.updated"
)

func (e PaymentUpdatedType) ToPointer() *PaymentUpdatedType {
	return &e
}
func (e *PaymentUpdatedType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "payment.updated":
		*e = PaymentUpdatedType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentUpdatedType: %v", v)
	}
}

type PaymentUpdatedRequestBody struct {
	// Payment amount
	Amount string             `json:"amount"`
	Type   PaymentUpdatedType `json:"type"`
}

func (o *PaymentUpdatedRequestBody) GetAmount() string {
	if o == nil {
		return ""
	}
	return o.Amount
}

func (o *PaymentUpdatedRequestBody) GetType() PaymentUpdatedType {
	if o == nil {
		return PaymentUpdatedType("")
	}
	return o.Type
}

type PaymentUpdatedResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PaymentUpdatedResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
