// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

type Error struct {
	Error_ string `json:"error"`
	Code   int64  `json:"code"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	return e.Error_
}
