// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type ErrorType2Error struct {
	Message string `json:"message"`
}

func (o *ErrorType2Error) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

type ErrorType2 struct {
	Error_   ErrorType2Error         `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ErrorType2{}

func (e *ErrorType2) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
