// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type ErrorType1 struct {
	Code     *string                 `const:"rate_limit_exceeded" json:"code"`
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ErrorType1{}

func (e *ErrorType1) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
